apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: zcgkhrl72-python
  janus-idp.io/tekton: zcgkhrl72-python
  backstage.io/kubernetes-id: zcgkhrl72-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: zcgkhrl72-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
